site_name: USTC高级计算机网络课程主页
# site_url: https://www.ustc.edu.cn
repo_name: ACN-2025/ACN-2025.github.io
repo_url: https://github.com/ACN-2025/ACN-2025.github.io
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences